"""Refactor onboarding table - remove university, gpa and add preferred_tech_stack, skill_confidence

Revision ID: 2c9aa7b0efd6
Revises: 7aadf0c51525
Create Date: 2025-06-19 16:18:03.415116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9aa7b0efd6'
down_revision = '7aadf0c51525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add columns as nullable
    op.add_column('onboarding_data', sa.Column('preferred_tech_stack', sa.JSON(), nullable=True))
    op.add_column('onboarding_data', sa.Column('skill_confidence', sa.String(), nullable=True))
    
    # Update existing rows with default values
    from sqlalchemy import text
    connection = op.get_bind()
    connection.execute(text("UPDATE onboarding_data SET preferred_tech_stack = '[]' WHERE preferred_tech_stack IS NULL"))
    connection.execute(text("UPDATE onboarding_data SET skill_confidence = 'Beginner' WHERE skill_confidence IS NULL"))
    
    # Now make columns not nullable
    op.alter_column('onboarding_data', 'preferred_tech_stack', nullable=False)
    op.alter_column('onboarding_data', 'skill_confidence', nullable=False)
    
    op.drop_column('onboarding_data', 'gpa')
    op.drop_column('onboarding_data', 'university')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_data', sa.Column('university', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('onboarding_data', sa.Column('gpa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('onboarding_data', 'skill_confidence')
    op.drop_column('onboarding_data', 'preferred_tech_stack')
    # ### end Alembic commands ### 