"""Add is_admin field to users

Revision ID: 4c08070b32c9
Revises: acb28e717e30
Create Date: 2025-07-06 16:31:26.278165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c08070b32c9'
down_revision: Union[str, None] = 'acb28e717e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_content', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('onboarding_data', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('roadmaps', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('roadmaps', 'is_admin')
    op.drop_column('onboarding_data', 'is_admin')
    op.drop_column('learning_content', 'is_admin')
    # ### end Alembic commands ###
