"""initial_migration

Revision ID: 5999b8cee5e5
Revises: cef59f27e7fc
Create Date: 2025-06-18 14:39:19.924104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5999b8cee5e5'
down_revision = 'cef59f27e7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('time_commitment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('learning_style', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeline', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('challenges', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='onboarding_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='onboarding_pkey')
    )
    # ### end Alembic commands ### 