"""Add is_bot column to users table

Revision ID: 5a046ac982cb
Revises: 0aaf0f8bb099
Create Date: 2025-07-28 17:47:02.589938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a046ac982cb'
down_revision: Union[str, None] = '0aaf0f8bb099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_bot')
    # ### end Alembic commands ###
