"""Fix is_active column to not allow null values

Revision ID: 625bb5fbfd23
Revises: 2c9aa7b0efd6
Create Date: 2025-06-19 16:44:52.374798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625bb5fbfd23'
down_revision = '2c9aa7b0efd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix existing NULL values in is_active column
    from sqlalchemy import text
    connection = op.get_bind()
    
    # Update any NULL is_active values to True
    connection.execute(text("UPDATE users SET is_active = TRUE WHERE is_active IS NULL"))
    
    # Make sure the column doesn't allow NULL values going forward
    op.alter_column('users', 'is_active', nullable=False, server_default='true')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Allow NULL values again (for rollback)
    op.alter_column('users', 'is_active', nullable=True, server_default=None)
    # ### end Alembic commands ### 