"""add_cascade_delete_to_foreign_keys

Revision ID: 658672577186
Revises: a48a492cb16e
Create Date: 2025-07-13 13:17:16.013057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658672577186'
down_revision: Union[str, None] = 'a48a492cb16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('learning_content_user_id_fkey', 'learning_content', type_='foreignkey')
    op.create_foreign_key(None, 'learning_content', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('onboarding_data_user_id_fkey', 'onboarding_data', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_data', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('roadmaps_user_id_fkey', 'roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'roadmaps', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.create_foreign_key('roadmaps_user_id_fkey', 'roadmaps', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'onboarding_data', type_='foreignkey')
    op.create_foreign_key('onboarding_data_user_id_fkey', 'onboarding_data', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'learning_content', type_='foreignkey')
    op.create_foreign_key('learning_content_user_id_fkey', 'learning_content', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
