"""Add onboarding table

Revision ID: 7aadf0c51525
Revises: 5999b8cee5e5
Create Date: 2025-06-19 15:33:44.664595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aadf0c51525'
down_revision = '5999b8cee5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 