"""add_is_public_field_to_topics

Revision ID: a429315b6d20
Revises: 5a046ac982cb
Create Date: 2025-07-30 11:27:48.502360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a429315b6d20'
down_revision: Union[str, None] = '5a046ac982cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first, then set default values, then make it NOT NULL
    op.add_column('topics', sa.Column('is_public', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE topics SET is_public = false WHERE is_public IS NULL")
    # Now make it NOT NULL
    op.alter_column('topics', 'is_public', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'is_public')
    # ### end Alembic commands ###
