"""add_pending_users_table

Revision ID: ab34f5b3d72f
Revises: 5b2346c560cf
Create Date: 2025-07-13 08:43:30.969998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab34f5b3d72f'
down_revision: Union[str, None] = '5b2346c560cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
