"""reflect model changes

Revision ID: acb28e717e30
Revises: 
Create Date: 2025-07-06 14:03:56.656888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acb28e717e30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration was causing issues on fresh deployments by trying to drop
    # tables/indexes that might not exist. We are emptying its upgrade block
    # to allow subsequent migrations to run without failure.
    # The actual schema changes will be applied by later migrations that create
    # the necessary tables and columns.
    pass
    # ### end Alembic commands ###

    # ### op.drop_table('email_verification_tokens', if_exists=True)
    # ### op.drop_column('users', 'email_verified')
    # ### end Alembic commands ##
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='email_verification_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='email_verification_tokens_pkey')
    )
    # ### end Alembic commands ###
