"""remove_target_internships_and_add_source_of_discovery

Revision ID: ebfb720c6169
Revises: 7a8202859a00
Create Date: 2025-07-07 15:22:48.041188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebfb720c6169'
down_revision: Union[str, None] = '7a8202859a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_data', sa.Column('source_of_discovery', sa.String(), nullable=True))
    op.drop_column('onboarding_data', 'target_internships')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_data', sa.Column('target_internships', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('onboarding_data', 'source_of_discovery')
    # ### end Alembic commands ###
