"""add_email_verification_fields

Revision ID: f82fb4efa70d
Revises: 5ac23e1c606b
Create Date: 2025-07-13 12:47:40.700829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82fb4efa70d'
down_revision: Union[str, None] = '5ac23e1c606b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pin_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pin_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin_expires')
    op.drop_column('users', 'pin_code')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
